const fs = require("fs");
const { JSDOM } = require("jsdom");
const html = fs.readFileSync("index.html","utf8");
const mockCtx = { fillStyle:null,fillRect:()=>{},strokeStyle:null,beginPath:()=>{},moveTo:()=>{},lineTo:()=>{},stroke:()=>{},arc:()=>{},fill:()=>{},createRadialGradient:()=>({addColorStop:()=>{}}),roundRect:()=>{},save:()=>{},restore:()=>{},globalAlpha:null,shadowColor:null,shadowBlur:null,font:null,textAlign:null,textBaseline:null,fillText:()=>{},setTransform:()=>{},clearRect:()=>{},translate:()=>{},rotate:()=>{},scale:()=>{},drawImage:()=>{},getImageData:()=>({data:[]}),putImageData:()=>{} };
const dom = new JSDOM(html,{url:"http://localhost",pretendToBeVisual:true,runScripts:"dangerously",beforeParse:function(win){win.HTMLCanvasElement.prototype.getContext=function(){return mockCtx};win.setTimeout=function(){};win.clearTimeout=function(){};win.setInterval=function(){return({})};win.clearInterval=function(){};win.AudioContext=function(){this.currentTime=0;this.destination={};var gain={gain:{value:0,exponentialRampToValueAtTime:function(){}},connect:function(){return{}}};this.createOscillator=function(){return{type:null,frequency:{value:0},connect:function(){return gain},start:function(){},stop:function(){}}};this.createGain=function(){return gain}};win.Audio=function(){};win.Audio.prototype.play=function(){return Promise.resolve()};win.Audio.prototype.pause=function(){};win.localStorage.getItem=function(){return null};win.localStorage.setItem=function(){};}});
const w = dom.window;
function c(e){try{return w.eval(e)}catch(e2){return "__ERR:"+e2.message}}
c("aiCount=1;speedVal=4;init()");
c("COLS=40;ROWS=30");
c("snakes[0]=[{x:5,y:5},{x:4,y:5},{x:3,y:5},{x:2,y:5}]");
c("snakes[1]=[{x:6,y:4},{x:6,y:3},{x:6,y:2}]");
c("ais[0]={dir:{x:0,y:1},nextDir:{x:0,y:1},score:0,name:'T'};aiBoosts[0]=0");
c("playerBoost=0");
c("moveSnake(1,{x:0,y:1})");
console.log("AI head:", c("snakes[1][0].x"), c("snakes[1][0].y"));
console.log("AI segments:", JSON.stringify(c("snakes[1]")));
c("window._playerDir={x:1,y:0}");
const r = c("moveSnake(0,window._playerDir)");
console.log("Result:", JSON.stringify(r));
console.log("Player:", "head at", c("snakes[0][0].x"), c("snakes[0][0].y"), "len", c("snakes[0].length"));
